FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY prototype /app/prototype

ENV PYTHONPATH=/app

CMD ["python", "-m", "prototype.edge.detector.main"]
